### PR TITLE
Added tvOS tests

### PR DESCRIPTION
**Pull request by bdrelling**

### CODE REVIEW

**Comment by aure** [comment]
So this one actually is not going to be able to be tvOS compatible because MIDI is too big a part of it.

**Comment by bdrelling** [comment]
@aure makes sense! The README currently shows `tvOS` as a heads up.

**Comment by aure** [comment]
I guess the README needs updating then, yeah.

**Comment by aure** [comment]
some of this should work on tvOS, so let me check something.

**Comment by aure** [comment]
These should pass if you merge upstream

**Review by aure — APPROVED** [review]

**Pull request merged**
